---
# add the javascript import statements for the component

- name: set component_js_imports
  vars.rb:
    vars:
      dir: "{{ qb_dir }}"
      elements: "{{ component_name_elements }}"
      
    # if the input is 
    # 
    #     dir: /Users/nrser/dev/gh/beiarea/wall/meteor
    #     elements: ['posts', 'wall', 'Overlay']
    # 
    # then we want the output to be
    # 
    #     [
    #         {
    #             "dest": "/Users/nrser/dev/gh/beiarea/wall/meteor/imports/ui/index.js",
    #             "line": "export const posts = require('./posts');"
    #         },
    #         {
    #             "dest": "/Users/nrser/dev/gh/beiarea/wall/meteor/imports/ui/posts/index.js",
    #             "line": "export const wall = require('./wall');"
    #         },
    #         {
    #             "dest": "/Users/nrser/dev/gh/beiarea/wall/meteor/imports/ui/posts/wall/index.js",
    #             "line": "export * from './Overlay.jsx';"
    #         }
    #     ]
    # 
    src: |
      namespace = elements[0...-1]
      class_name = elements[-1]
      
      $prefix = [dir, 'imports', 'ui']
      index_filename = "index.js"
      $imports = []
      
      def to_path *paths
        File.join paths.map {|_| [*_] }.flatten
      end
      
      def add dest_rel_path, line
        $imports << {
          dest: to_path($prefix, dest_rel_path),
          line: line,
        }
      end
      
      namespace.each_with_index {|item, index|      
        add [namespace[0...index], index_filename],
            "export const #{ item } = require('#{ to_path('.', item) }');"
      }
      
      add [namespace, index_filename],
          "export * from '#{ to_path('.', "#{ class_name }.jsx") }';"
      
      {component_js_imports: $imports}

- name: add javscript import lines
  lineinfile:
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
    create: true
  with_items: "{{ component_js_imports }}"