---  
- name: set the name elements
  set_fact:
    component_name_elements: "{{ component_name.split('.') }}"

- name: set the class name
  set_fact:
    component_class: "{{ component_name_elements[-1] }}"

- name: set the filepath
  set_fact:
    component_filepath: "{{ qb_dir }}/imports/ui/{{ component_name_elements | join('/') }}.jsx"

- name: set the directory
  set_fact:
    component_dir: "{{ component_filepath | dirname }}"

- name: set logger name
  set_fact:
    component_logger_name: "imports:ui:{{ component_name_elements | join(':') }}"

- name: set the css class name
  set_fact:
    component_css_class: "{{ component_name_elements | join('-') }}"

- name: create component directory
  file:
    path: "{{ component_dir }}"
    state: directory
    recurse: true

- name: "create {{ component_class }} component"
  template:
    src: component.jsx.j2
    dest: "{{ component_filepath }}"
    force: "{{ component_force }}"

- name: create a blaze wrapper for it
  template:
    src: wrapper.html.j2
    dest: "{{ component_dir }}/{{ component_class }}.html"
    force: "{{ component_force }}"
  when: component_blaze

- include: less.yml
  when: component_less

- include: import.yml
  when: component_import